[deps]
AoC = "54704efd-ff65-419d-94d2-d343f7b8a6f1"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
